{{- if .Values.webhookApp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beabee.fullname" . }}-webhook-app
  labels:
    {{- include "beabee.labels" . | nindent 4 }}
    component: webhook-app
spec:
  replicas: {{ .Values.webhookApp.replicaCount }}
  selector:
    matchLabels:
      {{- include "beabee.selectorLabels" (dict "component" "webhook-app") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "beabee.selectorLabels" (dict "component" "webhook-app") | nindent 8 }}
    spec:
      containers:
        - name: webhook-app
          image: beabee/beabee-webhook-app:{{ .Values.image.tag }}
          envFrom:
            - secretRef:
                name: {{ include "beabee.secretName" . }}
          {{- with (include "beabee.secretRefEnv" .) }}
          env:
            {{- . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 3000
          resources:
            {{- toYaml .Values.webhookApp.resources | nindent 12 }}
{{- end }}
