{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beabee.fullname" . }}-frontend
  labels:
    {{- include "beabee.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "beabee.selectorLabels" (dict "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "beabee.podLabels" (dict "component" "frontend") | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: beabee/beabee-frontend:{{ .Values.image.tag | default .Chart.AppVersion }}
          env:
            - name: APP_BASE_URL
              value: {{ printf "%s://%s" (include "beabee.scheme" .) .Values.hive.domain | quote }}
            - name: API_BASE_URL
              value: /api/1.0
            - name: CNR_MODE
              valueFrom:
                secretKeyRef:
                  name: {{ include "beabee.secretName" . }}
                  key: BEABEE_CNR_MODE
                  optional: true
            - name: APPSIGNAL_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "beabee.secretName" . }}
                  key: BEABEE_APPSIGNAL_KEY
                  optional: true
            - name: CAPTCHAFOX_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "beabee.secretName" . }}
                  key: BEABEE_CAPTCHAFOX_KEY
                  optional: true
            - name: MAPTILER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "beabee.secretName" . }}
                  key: BEABEE_MAPTILER_KEY
                  optional: true
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}
