apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beabee.fullname" . }}-cron-app
  labels:
    {{- include "beabee.labels" . | nindent 4 }}
    component: cron-app
spec:
  replicas: {{ .Values.cronApp.replicaCount }}
  selector:
    matchLabels:
      {{- include "beabee.selectorLabels" (dict "component" "cron-app") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "beabee.selectorLabels" (dict "component" "cron-app") | nindent 8 }}
    spec:
      containers:
        - name: cron-app
          image: beabee/beabee-cron-app:{{ .Values.image.tag }}
          envFrom:
            - configMapRef:
                name: {{ include "beabee.fullname" . }}-config
            - secretRef:
                name: {{ include "beabee.secretName" . }}
          {{- with (include "beabee.secretRefEnv" .) }}
          env:
            {{- . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.cronApp.resources | nindent 12 }}
